[package]
name = "ayatori-rbc"
version = "0.1.0"
edition = "2024"
license = "MIT"
authors = ['Bogdan Opanchuk <bogdan@opanchuk.net>']
description = "Ayatori-based reliable broadcast protocol"
repository = "https://github.com/fjarri/ayatori"
readme = "README.md"
categories = ["cryptography", "no-std"]
rust-version = "1.91"

[dependencies]
ayatori = { path = "../ayatori" }
reed-solomon-simd = "3"
serde-encoded-bytes = "0.2"
itertools = "0.14"
serde = { version = "1", default-features = false, features = ["alloc", "derive"] }
derive-where = { version = "1.5", default-features = false, features = ["serde"] }

[dev-dependencies]
ayatori = { path = "../ayatori", features = ["dev"] }
rand_chacha = { version = "0.10", default-features = false }

[lints]
workspace = true
