[workspace]
resolver = "3"
members = ["ayatori", "book-examples", "integration-tests"]

[workspace.lints.clippy]
all = { level = "warn", priority = -1 }
pedantic = { level = "warn", priority = -1 }
nursery = { level = "warn", priority = -1 }

# Disabling this due to too much noise.
# We are not really interested in internal functions being const or not.
missing_const_for_fn = "allow"

# Good idea, but if you implement this change,
# the compiler complains about a `pub(crate)` item being exported as `pub`.
redundant_pub_crate = "allow"

# Too restrictive, sometimes there's not need to specifically describe errors.
missing_errors_doc = "allow"

# We have some big methods.
too_many_lines = "allow"

mod_module_files = "warn"
unwrap_used = "warn"
indexing_slicing = "warn"

[workspace.lints.rust]
rust_2018_idioms = { level = "warn" }
missing_copy_implementations = { level = "warn" }
missing_debug_implementations = { level = "warn" }
trivial_casts = { level = "warn" }
trivial_numeric_casts = { level = "warn" }
missing_docs = { level = "warn" }
unused_qualifications = { level = "warn" }
