[workspace]
resolver = "3"
members = ["ayatori", "ayatori-rbc", "book-examples", "integration-tests"]

[workspace.lints.clippy]
all = { level = "warn", priority = -1 }
pedantic = { level = "warn", priority = -1 }
nursery = { level = "warn", priority = -1 }
perf = { level = "warn", priority = -1 }
suspicious = { level = "warn", priority = -1 }
correctness = { level = "warn", priority = -1 }
complexity = { level = "warn", priority = -1 }
style = { level = "warn", priority = -1 }

# Disabling this due to too much noise.
# We are not really interested in internal functions being const or not.
missing_const_for_fn = "allow"

# Good idea, but if you implement this change,
# the compiler complains about a `pub(crate)` item being exported as `pub`.
redundant_pub_crate = "allow"

# Too restrictive, sometimes there's not need to specifically describe errors.
missing_errors_doc = "allow"
missing_panics_doc = "allow" # also triggers on `expect()`

# We have some big methods.
too_many_lines = "allow"

# Doesn't work. See https://github.com/rust-lang/rust-clippy/issues/13918
doc_include_without_cfg = "allow"

# Select warning from the `restriction` category.
alloc_instead_of_core = "warn"
allow_attributes = "warn"
arithmetic_side_effects = "warn"
as_conversions = "warn"
indexing_slicing = "warn"
mod_module_files = "warn"
unwrap_used = "warn"

[workspace.lints.rust]
rust_2018_idioms = { level = "warn" }
missing_copy_implementations = { level = "warn" }
missing_debug_implementations = { level = "warn" }
trivial_casts = { level = "warn" }
trivial_numeric_casts = { level = "warn" }
missing_docs = { level = "warn" }
unused_qualifications = { level = "warn" }
