[package]
name = "ayatori"
version = "0.0.1"
edition = "2024"
license = "MIT"
authors = ['Bogdan Opanchuk <bogdan@opanchuk.net>']
description = "Graph-based framework for distributed cryptographic protocols"
repository = "https://github.com/fjarri/ayatori"
readme = "../README.md"
categories = ["cryptography", "no-std"]
rust-version = "1.90"

[dependencies]
derive-where = "1"
itertools = "0.14"
rand_core = { version = "0.9", default-features = false }

[dev-dependencies]
rand_chacha = { version = "0.9", default-features = false }

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
